### ISSUE TITLE
Unable to run- Error Unable to find this module 

### ISSUE THREAD

**Issue by yarnball** [corasan/Lotus#1]
Hi,

Looks like a great project.

However, I can't seem to build it. I get the error "Users/x/index.ios.js Unable to find this module in its module map or any of the node_modules directories under /Users/x/src/scenes/Posts and its parent diretories"

It could be basic- I'm very new to RN.

Here's what I've done (I've tried with the Main & Master branches):

1. ```git clone -b main --single-branch https://github.com/corasan/Lotus.git LotusRN```
2. ```npm install```
3. ```react-native run-ios```

**Comment by corasan** [comment]
That is because index.ios.js is looking for Posts in a path that doesn't exist. I was working on index.android.js so I never changed the the ios version when I changed my file structure

**index.android.js**
`import Posts from './src/Posts/Posts';`

**index.ios.js**
`import Posts from './src/scenes/Posts';`

So just change the `import` to the correct path. I didn't work on the ios version so it doesn't look how it's supposed to.

**Comment by yarnball** [comment]
Thanks- I copied needed to copy the entire index.android.ios.js contents to get it to run.

However, I'm now getting a `can't find variable firebase` error.

**Comment by corasan** [comment]
`import firebase from firebaseInit.js`

I'm importing firebaseInit.js which is a file with my firebase configuration and api key(private file). You have to create a new file with your firebase configuration.

Also, if you get it working keep in mind that the design will definitely look weird because there are a lot of design differences between platforms.

**Comment by corasan** [comment]
Also, if you get it working keep in mind that the design will definitely look weird because there are a lot of design differences between platforms.
